
<?php echo $this->render('widgets/global-search.phtml'); ?>
<!-- Slider -->
<?php echo $this->render('index/widgets/slider.phtml'); ?>


<div class="container">

    <div class="row mt-xlg">

        <div class="center_column col-xs-12 col-sm-12" id="center_column">
            <!-- view-product-list-->
            <div id="view-product-list" class="view-product-list mt-none">
                <div class="div_group">
                    <div class="div_menu">
                        <a href="/tim-kiem" style="color:White;"><b>TIN CHO THUÊ</b></a>
                    </div>
                </div>
                <!-- PRODUCT LIST -->
                <ul class="row product-list list mt-sm">
                    <?php foreach ($this->productData as $key => $product) { ?>

                    <li class="col-sx-12 col-sm-4" style="margin-top:15px;">
                        <div class="product-container mt-none" style="border: 1px solid #ddd;">
                            <div class="left-block" >
                                <a href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/'.$this->districtIdentify($product[DbTable_Product::COL_FK_DISTRICT]).'/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>" style="border: 1px solid #ddd;">
                                    <img class="img-responsive real-estate" alt="xome" src="<?php echo $this->showImageUrl($product[DbTable_Product::COL_PRODUCT_THUMB_NAIL], !$product[DbTable_Product::COL_PRODUCT_FLAG_UPLOAD_IMAGE],345, $product[DbTable_Product::COL_PRODUCT_FLAG_CROP]);?>"/>
                                </a>

                                <div class="product-price">
                                    <?php echo  $product[DbTable_Product::COL_PRODUCT_PAID_PRICE] > 500 ? number_format($product[DbTable_Product::COL_PRODUCT_PAID_PRICE]).' VND' : 'Thỏa thuận' ?>

                                </div>
                                <div class="date-add">
                                    <?php echo $this->formatTime($product[DbTable_Product::COL_PRODUCT_CREATED_AT]); ?>
                                </div>
                            </div>
                            <div class="right-block">
                                <h5 class="product-name"><a href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/'.$this->districtIdentify($product[DbTable_Product::COL_FK_DISTRICT]).'/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>"><?php echo $product[DbTable_Product::COL_PRODUCT_NAME]?></a></h5>

                                <div class="info-orther">
                                    <!--<p>Mã tin: #<?php /*echo $this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]);*/?></p>-->
                                    <p class="availability">Địa chỉ: <span><?php echo $product[DbTable_Product::COL_PRODUCT_ADDRESS]?></span></p>
                                    <p class="">Diện tích: <?php echo ($product[DbTable_Product::COL_PRODUCT_AREA]);?> m<sub>2</sub></p>
                                    <!--<div class="product-desc mt-none">
                                        <?php /*echo $product[DbTable_Product::COL_PRODUCT_SHORT_DESCRIPTION]*/?>
                                    </div>-->
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php } ?>


                </ul>
                <!-- ./PRODUCT LIST -->
            </div>
            <!-- ./view-product-list-->
            <div class="sortPagiBar">
                <div class="bottom-pagination">
                    <nav>
                        <?php echo $this->pagination;?>
                    </nav>
                </div>
            </div>
        </div>
        <!-- ./ Center colunm -->
    </div>

</div>