<div role="main" class="main">
    <!-- Slider -->
    <div class="slider-container light rev_slider_wrapper">
        <div id="revolutionSlider" class="slider rev_slider" data-plugin-revolution-slider data-plugin-options="{'delay': 9000, 'gridwidth': 1170, 'gridheight': 500, 'disableProgressBar': 'on'}">
            <ul>
                <li data-transition="fade">

                    <img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp"  
                        alt=""
                        data-bgposition="center center" 
                        data-bgfit="cover" 
                        data-bgrepeat="no-repeat" 
                        data-kenburns="on"
                        data-duration="9000"
                        data-ease="Linear.easeNone"
                        data-scalestart="150"
                        data-scaleend="100"
                        data-rotatestart="0"
                        data-rotateend="0"
                        data-offsetstart="0 0"
                        data-offsetend="0 0"
                        data-bgparallax="0"
                        class="rev-slidebg">

                    <div class="tp-caption"
                        data-x="177"
                        data-y="188"
                        data-start="1000"
                        data-transform_in="x:[-300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp" alt=""></div>

                    <div class="tp-caption top-label"
                        data-x="227"
                        data-y="180"
                        data-start="500"
                        data-transform_in="y:[-300%];opacity:0;s:500;">PHÒNG TRỌ CHẬT TRỌI</div>

                    <div class="tp-caption"
                        data-x="480"
                        data-y="188"
                        data-start="1000"
                        data-transform_in="x:[300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp" alt=""></div>

                    <div class="tp-caption main-label"
                        data-x="135"
                        data-y="210"
                        data-start="1500"
                        data-whitespace="nowrap"                         
                        data-transform_in="y:[100%];s:500;"
                        data-transform_out="opacity:0;s:500;"
                        data-mask_in="x:0px;y:0px;">BẠN CẦN CHUYỂN PHÒNG ?</div>

                    <div class="tp-caption bottom-label"
                        data-x="185"
                        data-y="280"
                        data-start="2000"
                        data-transform_in="y:[100%];opacity:0;s:500;">Xome.vn cung cấp cho bạn cách tiếp cận các phòng trọ nhanh nhất.</div>
                    
                </li>
                <li data-transition="fade">

                    <img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp"  
                        alt=""
                        data-bgposition="right center"
                        data-bgpositionend="center center"
                        data-bgfit="cover" 
                        data-bgrepeat="no-repeat" 
                        data-kenburns="on"
                        data-duration="9000"
                        data-ease="Linear.easeNone"
                        data-scalestart="110"
                        data-scaleend="100"
                        data-rotatestart="0"
                        data-rotateend="0"
                        data-offsetstart="0 0"
                        data-offsetend="0 0"
                        data-bgparallax="0"
                        class="rev-slidebg">

                    <div class="tp-caption featured-label"
                        data-x="center"
                        data-y="210"
                        data-start="500"
                        style="z-index: 5"
                        data-transform_in="y:[100%];s:500;"
                        data-transform_out="opacity:0;s:500;">CHÀO MỪNG ĐẾN XOME.VN</div>

                    <div class="tp-caption bottom-label"
                        data-x="center"
                        data-y="270"
                        data-start="1000"
                        data-transform_idle="o:1;"
                        data-transform_in="y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;s:600;e:Power4.easeInOut;"
                        data-transform_out="opacity:0;s:500;"
                        data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                        data-splitin="chars" 
                        data-splitout="none" 
                        data-responsive_offset="on"
                        style="font-size: 23px; line-height: 30px;"
                        data-elementdelay="0.05">Chúng tôi rất hấn hạnh được phục vụ quý khách</div>

                </li>
            </ul>
        </div>
    </div>
    
    <?php echo $this->render('index/widgets/search-box_.phtml'); ?>


    <div class="home-intro light" id="home-intro">
        <div class="container">

            <div class="row">
                <div class="col-md-8">
                    <p>
                        Quý khách có thể tham gia nhóm <em> <a href="https://www.facebook.com/groups/thuephongtrohcm/">Thuê
                                trọ Hồ Chí Minh</a></em> trên Facebook
                        <span>Với hơn 70.000 thành viên và hơn 1.000 bài viết mỗi ngày.</span>
                    </p>
                </div>
                <div class="col-md-4">
                    <div class="get-started">
                        <a href="https://www.facebook.com/groups/thuephongtrohcm/" class="btn btn-lg btn-primary">Tham
                            gia ngay!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="row mt-xlg">
            <!-- Left colunm -->
            <!-- <div class="column col-xs-12 col-sm-3" id="left_column">
            <?php /*echo $this->render('widgets/sidebar-left.phtml'); */?>




        </div>-->
            <!-- ./left colunm -->
            <!-- Center colunm-->
            <div class="center_column col-xs-12 col-sm-12" id="center_column">
                <!-- view-product-list-->
                <div id="view-product-list" class="view-product-list mt-none">
                    <h2 class="page-heading center">
                        <span class="page-heading-title">TIN CHO THUÊ MỚI ĐĂNG</span>
                    </h2>
                    <!--<div class="sortPagiBar" style="position: absolute;right: 0;top: 0;margin-top: 0px;">
                        <div class="sort-product">
                            <select>
                                <option value="">Mặc định</option>
                                <option value="">Giá thuê</option>
                                <option value="">Lượt xem</option>
                            </select>
                            <div class="sort-product-icon">
                                <i class="fa fa-sort-alpha-asc"></i>
                            </div>
                        </div>
                    </div>-->
                    <!-- PRODUCT LIST -->

                    <div class="row product-list list mt-sm">
                        <?php foreach ($this->productData as $key => $product) { ?>

                            <div class="col-md-4 product-item">
                                <span class="thumb-info thumb-info-preview thumb-info-preview-long">
                                    <span class="thumb-info-wrapper">
                                        <!--<span class="thumb-info-image" data-original="img/previews/preview-corporate-version8.jpg" data-plugin-lazyload="" style="display: block; background-image: url(&quot;img/previews/preview-corporate-version8.jpg&quot;);"></span>-->
                                        <a class=""
                                           href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($product[DbTable_Product::COL_FK_DISTRICT]) . '/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' . $this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>">
                                            <img class="thumb-info-image"
                                                 src="<?php echo $this->showImageUrl($product[DbTable_Product::COL_PRODUCT_THUMB_NAIL], !$product[DbTable_Product::COL_PRODUCT_FLAG_UPLOAD_IMAGE],350, $product[DbTable_Product::COL_PRODUCT_FLAG_CROP]); ?>"
                                                 alt="<?php echo $product[DbTable_Product::COL_PRODUCT_NAME] ?>"
                                                 height="100">
                                        </a>
                                        <div class="figType"><a
                                                href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]); ?>.html"><?php echo $this->productCategoryLabel($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]); ?></a>
                                        </div>
                                        <div class="figPrice" style="font-weight:700;">
                                            <?php echo $product[DbTable_Product::COL_PRODUCT_PAID_PRICE] > 1000 ? number_format($product[DbTable_Product::COL_PRODUCT_PAID_PRICE]) . ' VND' : 'Thỏa thuận' ?>
                                        </div>
                                    </span>
                                </span>

                                <div class="recent-posts pt-md mb-lg" style="border: 1px solid #DDD; border-top: none;">
                                    <article class="post mr-sm ml-sm">
                                        <h5 class="mb-xs course-title" style="min-height: 35px;">
                                            <a class=""
                                               href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($product[DbTable_Product::COL_FK_DISTRICT]) . '/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' . $this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>"><?php echo $product[DbTable_Product::COL_PRODUCT_NAME] ?></a>
                                        </h5>

                                        <div style="min-height: 50px;">
                                            Địa chỉ:
                                            <span><?php echo $product[DbTable_Product::COL_PRODUCT_ADDRESS] ?></span>
                                        </div>

                                        <div class="post-meta">
                                            <span><i
                                                    class="fa fa-calendar"></i> <?php echo $this->formatTime($product[DbTable_Product::COL_PRODUCT_CREATED_AT]); ?> </span>
                                            <span><i
                                                    class="fa fa-phone"></i>  <?php echo $product[DbTable_Product::COL_PRODUCT_PHONE]; ?></span>


                                        </div>
                                        <div class="post-meta-action">
                                            <div class="cf_teacher">
                                                <div class="cf_ava"><span
                                                        style="background-image: url(<?php echo $product[DbTable_Product_Own::COL_PRODUCT_OWN_FACEBOOK_ID] ? 'https://graph.facebook.com/' . $product[DbTable_Product_Own::COL_PRODUCT_OWN_FACEBOOK_ID] . '/picture?type=large' : 'http://static.' . Application_Constant_Global::DOMAIN . '/upload/default/no-avatar.png'; ?>)"></span>
                                                </div>
                                                <div class="cf_t_n"><a
                                                        href="/thong-tin-nguoi-dang/<?php echo Application_Function_String::getFormatUrl(Application_Function_String::convertNoVn($product[DbTable_Product::COL_PRODUCT_PHONE])) . '-' . strtolower($this->productOwnerEncode($product[DbTable_Product::COL_FK_PRODUCT_OWNER])) . '.html'; ?>"
                                                        target="_blank"><?php echo $product[DbTable_Product::COL_FK_PRODUCT_OWNER] && $product[DbTable_Product_Own::COL_PRODUCT_OWN_NAME] != '' ? $product[DbTable_Product_Own::COL_PRODUCT_OWN_NAME] : $product[DbTable_Product::COL_PRODUCT_PHONE]; ?></a>
                                                        <span class="" style="float:right"><i class="fa fa-eye"></i> <?php echo  $product[DbTable_Product::COL_PRODUCT_PAGEVIEW]; ?></span>
                                                </div>
                                               
                                            </div>


                                        </div>
                                    </article>
                                </div>
                            </div>


                        <?php } ?>
                    </div>
                    <!-- ./PRODUCT LIST -->
                </div>
                <!-- ./view-product-list-->
                <div class="sortPagiBar mb-md">
                    <div class="bottom-pagination pull-right">
                        <a class="btn btn-default btn_search_box  blue-steel" href="/tim-kiem?page=2">Xem thêm</a>
                    </div>
                </div>
                <div class="mt-xl mb-md"></div>
                <hr>
                <div id="view-contact-list" class="view-product-list">
                    <h2 class="page-heading center">
                        <span class="page-heading-title">TIN TÌM PHÒNG</span>
                    </h2>

                    <!-- CONTACT LIST -->

                    <div class="row product-list list mt-sm">
                        <?php foreach ($this->contactData as $key => $contact) { ?>

                            <div class="col-md-4 product-item">
                                <span class="thumb-info thumb-info-preview thumb-info-preview-long">
                                    <span class="thumb-info-wrapper">
                                        <!--<span class="thumb-info-image" data-original="img/previews/preview-corporate-version8.jpg" data-plugin-lazyload="" style="display: block; background-image: url(&quot;img/previews/preview-corporate-version8.jpg&quot;);"></span>-->
                                        <a href="/tin-tim-phong/<?php echo Application_Function_String::getFormatUrl($contact[DbTable_Contact::COL_CONTACT_ADDRESS]) . '-' . strtolower($this->contactEncode($contact[DbTable_Contact::COL_CONTACT_ID])) . '.html'; ?>">
                                            <img class="img-responsive"
                                                 src="<?php echo $contact[DbTable_Contact::COL_CONTACT_URL_STATIC_MAP] ? $contact[DbTable_Contact::COL_CONTACT_URL_STATIC_MAP] : '/upload/backgrounds/no-image-box.png'; ?>"
                                                 alt="<?php echo $contact[DbTable_Contact::COL_CONTACT_ADDRESS]; ?>"
                                                 title="<?php echo $contact[DbTable_Contact::COL_CONTACT_ADDRESS]; ?>">
                                        </a>
                                        <div class="figType"><a
                                                href="/"><?php echo $contact[DbTable_Contact::COL_CONTACT_NAME]; ?></a>
                                        </div>
                                        <div class="figPrice">
                                            <?php echo $contact[DbTable_Contact::COL_CONTACT_PHONE]?>
                                        </div>
                                    </span>
                                </span>

                                <div class="recent-posts pt-md mb-lg" style="border: 1px solid #DDD; border-top: none;">
                                    <article class="post mr-sm ml-sm">
                                        <h5 class="mb-xs course-title" style="min-height: 35px;">
                                            <a class=""
                                               href="/tin-tim-phong/<?php echo Application_Function_String::getFormatUrl($contact[DbTable_Contact::COL_CONTACT_ADDRESS]) . '-' . strtolower($this->contactEncode($contact[DbTable_Contact::COL_CONTACT_ID])) . '.html'; ?>">Cần tìm phòng <?php echo $contact[DbTable_Contact::COL_CONTACT_ADDRESS] ?></a>
                                        </h5>


                                    </article>
                                </div>
                            </div>


                        <?php } ?>
                    </div>
                    <!-- ./CONTACT LIST -->
                </div>

                <div class="sortPagiBar">
                    <div class="bottom-pagination pull-right">
                        <a class="btn btn-default btn_search_box  blue-steel" href="/tin-tim-phong.html">Xem thêm</a>
                    </div>
                </div>
            </div>
            <!-- ./ Center colunm -->
        </div>

    </div>



</div>