<div class="container">

    <div class="row">
        <div class="col-md-12">

            <div class="featured-boxes">
                <div class="row">
                    <div class="col-sm-3">

                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-default  mt-xlg">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <i class="fa fa-plus-square"></i>
                                    Đăng nhập

                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse">
                                <div class="panel-body">
                                    <div style="text-align: center;">
                                        <div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false" onlogin="checkLoginState();" scope="public_profile,email"></div>
                                    </div>
                                    <p class="text-center mt-sm mb-sm">Hoặc</p>

                                    <div class="featured-box featured-box-primary align-left mt-xlg">
                                        <div class="box-content">
                                            <h4 class="heading-primary text-uppercase mb-md">Bạn đã có tài khoản</h4>
                                            <form action="/customer/submit-login" id="frmSignIn" method="post">
                                                <div class="row">
                                                    <div class="form-group">
                                                        <div class="col-md-12">
                                                            <label>E-mail</label>
                                                            <input type="email" value="" class="form-control input-lg"  name="email"  maxlength="256" minlength="6" email required>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="form-group">
                                                        <div class="col-md-12">
                                                            <!--<a class="pull-right" href="/tai-khoan/quen-mat-khau.html">( Quên mật khẩu? )</a>-->
                                                            <label>Mật khẩu</label>
                                                            <input type="password" value="" class="form-control input-lg"  name="password" required minlength="6" maxlength="32">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                            <span class="remember-box checkbox">
                                                <label for="rememberme">
                                                    <input type="checkbox" id="rememberme" name="remember">Tự động đăng nhập lần sau
                                                </label>
                                            </span>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group  pull-right">
                                                            <?php echo $this->formHidden('backUrl', $this->backUrl ? $this->backUrl : $this->backUrl);?>
                                                            <a href="/tai-khoan/dang-ky.html" class="btn btn-default mt-sm">Đăng ký</a>
                                                            <input type="submit" value="Đăng nhập" class="btn btn-primary mt-sm" data-loading-text="Loading...">
                                                        </div>

                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">

                    </div>


                </div>

            </div>
        </div>
    </div>

</div>


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1428898624081256',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.11'
    });
      
    FB.AppEvents.logPageView();   
   
    
  };
  function checkLoginState() {
      FB.getLoginStatus(function(response) {
        window.location.href  ='http://xome.vn/customer/callback?accessToken=' +response['authResponse']['accessToken']
        console.log(response);
      });
    }

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>