<div id="global_search_box" class="">
    <div class="search_box_wrapper">
        <div class="container-fluid">
            <div class="search_box_form_wrapper pt-md">

                <form role="search" method="GET" id="searchformTop" class="searchform" action="/tim-kiem">
                    <div class="search_field">
                        <div class="row">
                            <div class="col-xs-10">
                                <div class="form-group">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="search_keyword" name="key" value="<?php echo isset($this->key) ? $this->key : null; ?>" placeholder="Nhập thông tin cần tìm">
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-2">
                                <div class="form-group  pull-right">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Tìm</button>
                                    </div>


                                </div>
                            </div>
                        </div>

                    </div></form>
            </div>
        </div>
    </div>
</div>