<div id="header" class="header" style="height: auto;min-height">


    <div class="nav-top-menu" id="nav-top-menu">
        <div class="container">
            <div class="row">

                <div id="main-menu" class="col-sm-12 col-md-12 main-menu">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="/" style=" color: #ffffff; font-weight: 700; font-size: 23px;">
                                    XOME.VN
                                </a>
                            </div>
                            <?php echo $this->render('widgets/menu.phtml'); ?>
                        </div>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</div>
