<div id="navbar" class="navbar-collapse collapse" style="margin-left: 15px;">
    <ul class="nav navbar-nav">
        <li class="<?php echo  !$this->menuHeader || $this->menuHeader ==  Application_Constant_Identify::MENU_HEADER_HOME ? 'active' : '';?>"><a href="/">TRANG CHỦ</a></li>

        <li class="<?php echo  $this->menuHeader ==  Application_Constant_Identify::MENU_HEADER_MOTEL ? 'active' : '';?>"><a href="/nha-cho-thue.html">NHÀ CHO THUÊ</a></li>
        <li class="<?php echo  $this->menuHeader ==  Application_Constant_Identify::MENU_HEADER_MOTEL_ROOM ? 'active' : '';?>"><a href="/phong-cho-thue.html">PHÒNG CHO THUÊ</a></li>
        <li class="<?php echo  $this->menuHeader ==  Application_Constant_Identify::MENU_HEADER_MOTEL_ROOM_TRANSPLANT ? 'active' : '';?>"><a href="/tim-nguoi-o-ghep.html">Ở GHÉP</a></li>

        <li><a href="/tin-tim-phong.html">NGUOI TÌM PHÒNG</a></li>
        <li style=""><a class="" href="/tim-kiem?<?php echo $this->queryPagination;?>"><i class="fa fa-map-marker"></i>&nbsp;TIM PHONG</a></li>
        <li style=""><a href="/dang-tin-cho-thue.html">ĐĂNG TIN CHO THUÊ</a></li>
        <!--<li class="pull-right"><a href="category.html" class="btn">ĐĂNG TIN</a></li>-->
    </ul>
</div><!--/.nav-collapse -->