<div class="columns-container">
    <div class="container" id="columns">

        <!-- breadcrumb -->
        <div class="breadcrumb clearfix">
            <a class="home" href="/" title="Return to Home">Trang chủ</a>
            <span class="navigation-pipe">&nbsp;</span>
            <span class="navigation_page">Nhà cho thuê</span>
        </div>
        <!-- ./breadcrumb -->

        <div class="row">
            <div class="col-md-3 hidden-xs" id="left_column">
                <?php echo $this->render('widgets/sidebar-left.phtml'); ?>
            </div>

            <div class="center_column col-xs-12 col-sm-9" id="center_column">
                <?php echo $this->render('widgets/register-real-estate.phtml'); ?>
                <!-- view-product-list-->
                <div id="view-product-list" class="view-product-list">
                    <div class="div_group">
                        <div class="div_menu">
                            <a href="#" style="color:White;"><b>TIN CHO THUÊ</b></a>
                        </div>
                    </div>

                    <ul class="row product-list list mt-sm">
                        <?php foreach ($this->productData as $key => $product) { ?>

                            <li class="col-sx-12 col-sm-4">
                                <div class="product-container mt-none">
                                    <div class="left-block">
                                        <a href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/quan-1/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>" style="border: 1px solid #ddd;">
                                            <img class="img-responsive real-estate" alt="<?php echo $product[DbTable_Product::COL_PRODUCT_NAME] ?>" src="<?php echo $this->showImageUrl($product[DbTable_Product::COL_PRODUCT_THUMB_NAIL], !$product[DbTable_Product::COL_PRODUCT_FLAG_UPLOAD_IMAGE]);?>"/>
                                        </a>

                                        <div class="product-price">
                                            <?php echo  $product[DbTable_Product::COL_PRODUCT_PAID_PRICE] > 500 ? number_format($product[DbTable_Product::COL_PRODUCT_PAID_PRICE]) : 'Thỏa thuận '?>

                                        </div>
                                        <div class="date-add">
                                            <?php echo $this->formatTime($product[DbTable_Product::COL_PRODUCT_CREATED_AT]); ?>
                                        </div>
                                    </div>
                                    <div class="right-block">
                                        <h5 class="product-name"><a
                                                href="/<?php echo $this->productCategoryIdentify($product[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/'. $this->districtIdentify($product[DbTable_Product::COL_FK_DISTRICT]) . '/' . $product[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?>"><?php echo $product[DbTable_Product::COL_PRODUCT_NAME] ?></a>
                                        </h5>


                                        <div class="info-orther">
                                            <p>Mã tin:
                                                #<?php echo $this->productEncode($product[DbTable_Product::COL_PRODUCT_ID]); ?></p>

                                            <p class="availability">Địa chỉ:
                                                <span><?php echo $product[DbTable_Product::COL_PRODUCT_ADDRESS] ?></span>
                                            </p>

                                            <p class="">Diện
                                                tích: <?php echo($product[DbTable_Product::COL_PRODUCT_AREA]); ?> m<sub>2</sub>
                                            </p>

                                            <div class="product-desc mt-none">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php } ?>


                    </ul>
                    <!-- ./PRODUCT LIST -->
                </div>
                <!-- ./view-product-list-->
                <div class="sortPagiBar">
                    <div class="bottom-pagination">
                        <?php echo $this->pagination;?>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>