<div style="background-color: #E2E2E2;">

    <div class="container">
        <div class="row">
            <div class="col-md-12 map-navigation-positioning">
                <div class="map-navigation-wrapper">
                    <div class="map-navigation">
                        <form role="search" method="GET" id="searchformTop_no_map" class="searchform" action="/tim-kiem">
                            <div class="search_field">
                                <div class="row">
                                    <div class="col-xs-3 padding5">
                                        <div class="form-group">
                                            <div class="form-group">
                                                <input type="text" class="form-control" id="search_keyword_1" name="key"
                                                       value="<?php echo isset($this->key) ? $this->key : null; ?>"
                                                       placeholder="Nhập thông tin cần tìm">
												<input type="hidden" id="lat"  name="lat">	   
												<input type="hidden" id="lng" name="lng">	   
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-xs-3 padding5">
                                        <div class="form-group">
                                            <?php echo $this->formSelect(
                                                'district',
                                                isset($this->district) ? $this->district : null,
                                                array(
                                                    'class' => 'form-control',
                                                    'id' => 'search_district'
                                                ),
                                                array(
                                                    '' => '--Chọn Quận--',
                                                    760 => 'Quận 1',
                                                    769 => 'Quận 2',
                                                    770 => 'Quận 3',
                                                    773 => 'Quận 4',
                                                    774 => 'Quận 5',
                                                    775 => 'Quận 6',
                                                    778 => 'Quận 7',
                                                    776 => 'Quận 8',
                                                    763 => 'Quận 9',
                                                    771 => 'Quận 10',
                                                    772 => 'Quận 11',
                                                    761 => 'Quận 12',
                                                    762 => 'Quận Thủ Đức',
                                                    764 => 'Quận Gò Vấp',
                                                    765 => 'Quận Bình Thạnh',
                                                    766 => 'Quận Tân Bình',
                                                    767 => 'Quận Tân Phú',
                                                    768 => 'Quận Phú Nhuận',
                                                    777 => 'Quận Bình Tân',
                                                    783 => 'Huyện Củ Chi',
                                                    784 => 'Huyện Hóc Môn',
                                                    785 => 'Huyện Bình Chánh',
                                                    786 => 'Huyện Nhà Bè',
                                                    787 => 'Huyện Cần Giờ',
                                                )
                                            ); ?>

                                        </div>
                                    </div>
                                    <div class="col-xs-3 padding5">
                                        <div class="form-group">
                                            <?php echo $this->formSelect(
                                                'price-value',
                                                isset($this->priceValue) ? $this->priceValue : null,
                                                array(
                                                    'class' => 'form-control price',
                                                    'id' => 'search_room_prices'
                                                ),
                                                array(
                                                    '' => '--Chọn mức giá--',

                                                    1 => '< 1.000.000',
                                                    2 => '1000.000 - 3.000.000',
                                                    3 => '3.000.000 - 5.000.000',
                                                    4 => '5.000.000 - 10.000.000',
                                                    5 => '> 10.000.000',

                                                )
                                            ); ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-3 padding5">
                                        <label class="radio-inline" style="color:white;">
                                            <input type="checkbox" name="type-search" id="type_search"
                                                   value="0" disabled>
                                            Xem bản đồ
                                        </label>

                                        <div class="form-group  pull-right">
                                            <button type="submit" class="btn btn-default btn_search_box_no_map  blue-steel">Tìm
                                                kiếm
                                            </button>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </form>
                    </div>
                    <!-- /.map-navigation -->
                </div>
                <!-- /.map-navigation-wrapper -->
            </div>
            <!-- /.col-sm-3 -->
        </div>
        <!-- /.row -->
    </div>
</div>