<div class="slider-container light rev_slider_wrapper">
        <div id="revolutionSlider" class="slider rev_slider" data-plugin-revolution-slider data-plugin-options="{'delay': 9000, 'gridwidth': 1170, 'gridheight': 500, 'disableProgressBar': 'on'}">
            <ul>
                <li data-transition="fade">

                    <img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp"  
                        alt=""
                        data-bgposition="center center" 
                        data-bgfit="cover" 
                        data-bgrepeat="no-repeat" 
                        data-kenburns="on"
                        data-duration="9000"
                        data-ease="Linear.easeNone"
                        data-scalestart="150"
                        data-scaleend="100"
                        data-rotatestart="0"
                        data-rotateend="0"
                        data-offsetstart="0 0"
                        data-offsetend="0 0"
                        data-bgparallax="0"
                        class="rev-slidebg">

                    <div class="tp-caption"
                        data-x="177"
                        data-y="188"
                        data-start="1000"
                        data-transform_in="x:[-300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp" alt=""></div>

                    <div class="tp-caption top-label"
                        data-x="227"
                        data-y="180"
                        data-start="500"
                        data-transform_in="y:[-300%];opacity:0;s:500;">PHÒNG TRỌ CHẬT TRỌI</div>

                    <div class="tp-caption"
                        data-x="480"
                        data-y="188"
                        data-start="1000"
                        data-transform_in="x:[300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp" alt=""></div>

                    <div class="tp-caption main-label"
                        data-x="135"
                        data-y="210"
                        data-start="1500"
                        data-whitespace="nowrap"                         
                        data-transform_in="y:[100%];s:500;"
                        data-transform_out="opacity:0;s:500;"
                        data-mask_in="x:0px;y:0px;">BẠN CẦN CHUYỂN PHÒNG ?</div>

                    <div class="tp-caption bottom-label"
                        data-x="185"
                        data-y="280"
                        data-start="2000"
                        data-transform_in="y:[100%];opacity:0;s:500;">Xome.vn cung cấp cho bạn cách tiếp cận các phòng trọ nhanh nhất.</div>
                    
                </li>
                <li data-transition="fade">

                    <img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/04-05-2018-09-24-45.webp"  
                        alt=""
                        data-bgposition="right center"
                        data-bgpositionend="center center"
                        data-bgfit="cover" 
                        data-bgrepeat="no-repeat" 
                        data-kenburns="on"
                        data-duration="9000"
                        data-ease="Linear.easeNone"
                        data-scalestart="110"
                        data-scaleend="100"
                        data-rotatestart="0"
                        data-rotateend="0"
                        data-offsetstart="0 0"
                        data-offsetend="0 0"
                        data-bgparallax="0"
                        class="rev-slidebg">

                    <div class="tp-caption featured-label"
                        data-x="center"
                        data-y="210"
                        data-start="500"
                        style="z-index: 5"
                        data-transform_in="y:[100%];s:500;"
                        data-transform_out="opacity:0;s:500;">CHÀO MỪNG ĐẾN XOME.VN</div>

                    <div class="tp-caption bottom-label"
                        data-x="center"
                        data-y="270"
                        data-start="1000"
                        data-transform_idle="o:1;"
                        data-transform_in="y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;s:600;e:Power4.easeInOut;"
                        data-transform_out="opacity:0;s:500;"
                        data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                        data-splitin="chars" 
                        data-splitout="none" 
                        data-responsive_offset="on"
                        style="font-size: 23px; line-height: 30px;"
                        data-elementdelay="0.05">Chúng tôi rất hấn hạnh được phục vụ quý khách</div>

                </li>
            </ul>
        </div>
    </div>